# Use rockon-validator repo to validate style and completeness of new Rockon submissions
# Thanks to @StephenBrown2 for donating original validation repository to the Rockstor project.

name: rockon-validator

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:
    - '*.json'
    
  pull_request:
    branches: [ "master" ]
    paths:
    - '*.json'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "validate"
  validate:
    name: rockon validator
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # install the latest version of Rockon validator
      - name: Setup latest Rockon validator
        run: |
         go install github.com/rockstor/rockon-validator@latest 

      - name: Get all changed json files
        id: changed-json-files
        uses: tj-actions/changed-files@v45
        with:
          # json files
          files: |
            **.json

# show differentials based on ideal Rockon schema and whether it's in the root.json file
      - name: Process all changed json files
        if: steps.changed-json-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-json-files.outputs.all_changed_files }}
        run: |
          for jsonfile in ${ALL_CHANGED_FILES}; do
            rockon-validator -d $jsonfile
          done
